---
- name: modify firewall
  gcp_compute_firewall:
    name: 'firewall-instance'
    allowed:
    - ip_protocol: tcp
      ports:
      - '22'
    source_ranges:
    - 0.0.0.0/0
    target_tags:
    - instancearino
    network: "{{ network }}"
    direction: ingress
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
        - https://www.googleapis.com/auth/compute
    state: "{{ state }}"
