---
- name: modify instance
  gcp_compute_instance:
    state: "{{ state }}"
    name: "{{ instance_name }}"
    machine_type: "{{ machine_type }}"
    deletion_protection: "{{ deletion_protection }}"
    metadata:
      ssh-keys: "{{ ssh_user }}:{{ ssh_key }}"
    disks:
      - auto_delete: true
        boot: true
        source: "{{ disk }}"
    network_interfaces:
      - network: "{{ network }}"
        access_configs:
          - name: 'External NAT'
            nat_ip: "{{ address }}"
            type: 'ONE_TO_ONE_NAT'
    tags:
      items:
        - instancearino
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
  register: instance
