---
- name: setup rustup
  include_role:
    name: ansible-rustup
  vars:
    rustup_user: gropius_user

# this is not needed if we're explicitly calling rustup
#- name: reboot
#  reboot:
#    reboot_timeout: 3600

# explicitly calling rustup because .bashrc doesn't get run
# over ssh in non-interactive mode, so rustup is not on path :S

- name: configure rustup
  shell: |
    ~/.cargo/bin/rustup default stable
    ~/.cargo/bin/rustup update nightly
    ~/.cargo/bin/rustup target add wasm32-unknown-unknown --toolchain nightly
  changed_when: false
  become: yes
  become_user: gropius_user
