---
# taken from https://getsubstrate.io
- name: install substrate apt requirements for ubuntu
  apt:
    pkg:
    - cmake
    - pkg-config
    - libssl-dev
    - git
    - gcc
    - build-essential
    - clang
    - libclang-dev

