---
dependency:
  name: galaxy
  options:
    role-file: ../../requirements/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: builder0
    groups:
      - builder_bin
    image: ubuntu:bionic
  - name: specer0
    groups:
      - builder_spec
    image: ubuntu:bionic
  - name: validator0
    image: jrei/systemd-ubuntu:18.04
    groups:
      - bootnode
      - validator
    privileged: true
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/sbin/init'
    network_mode: host
    environment:
      container: docker
  - name: validator1
    image: jrei/systemd-ubuntu:18.04
    groups:
      - validator
    privileged: true
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/sbin/init'
    network_mode: host
    environment:
      container: docker
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        substrate_repository: 'https://github.com/substrate-developer-hub/substrate-node-template'
        substrate_repository_version: '8b6fe66'
        substrate_network_id: local_testnet
        substrate_use_default_spec: true
        substrate_bin_name: node-template
        substrate_node_name: gantree-yeetbox
        substrate_user: subuser
        substrate_group: subgroup
        substrate_bootnode_argument:
          - '/ip4/35.242.216.93/tcp/30333/p2p/QmeoT4nzw5QDRaqdkBfnaqW9grMTLiEuYUpu4hSbseKB8C'
          - '/ip4/34.89.161.185/tcp/30333/p2p/QmbNXcLkbD7Z2BaSUTfqb1VEkEDTij9rhS79b8F2uiJ3Ki'
          - '/ip4/35.246.201.166/tcp/30333/p2p/QmX1hSCYFgeW876VQvWYkkmxon91ofvsnmk8ceCk1i8Tyv'
          - '/ip4/35.242.226.138/tcp/30333/p2p/QmW2NQVT1nLqAJCsxXixHkuCN93bCbbdminYKNSGyEX77R'
        gantree_control_working: /tmp/gantree-control
        gantree_root: ../../../../../
      builder_bin:
        gantree_working: /tmp/gantree-build-bin
      builder_spec:
        gantree_working: /tmp/gantree-build-spec
      validator:
        gantree_working: /home/subuser/tmp/gantree-validator
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
