---
- name: setup cargo and rustup
  include_role:
    name: ansible-role-cargo

- name: configure rustup
  shell: |
    rustup default stable
    rustup update nightly
    rustup target add wasm32-unknown-unknown --toolchain nightly
  changed_when: false
