- name: stop substrate
  become: yes
  systemd:
    name: substrate
    state: stopped

- name: clean substrate db
  become: yes
  shell: |
    if [ {{ substrate_chain_argument }} != "false" ]; then
      chain=" --chain={{ substrate_chain_argument }}"
    else
      chain=""
    fi

    nochain="{{ substrate_bin_name }} purge-chain -d /home/{{ substrate_user }}/.local/share/{{ substrate_bin_name }} -y"
    command="$nochain$chain"

    eval $command

- name: start substrate
  become: yes
  systemd:
    name: substrate
    state: started
