---
- import_tasks: 0_select.yml
  vars:
    access_token: "{{ config.access_token }}"
    ssh_user: root
    ssh_key: "{{ config.ssh_key }}"
    instance_name: "{{ config.instance_name }}"
    droplet_size: "{{ config.droplet_size | default('s-1vcpu-1gb') }}"
    droplet_image: '53893572' # ubuntu-18-04-x64
    region: "{{ config.droplet_region | default('nyc3') }}"
    state: "{{ config.state | default('present') }}"
