---
- name: get bootnode public ip
  ipify_facts:
  register: bootnode_ip

- name: replace bootnode loopback ip with public ip
  delegate_to: localhost
  replace:
    path: '{{gantree_control_working}}/spec/chainSpecRaw.raw'
    regexp: '127.0.0.1'
    replace: '{{ bootnode_ip.ansible_facts.ipify_public_ip }}'
  when: (not is_docker is defined) or (not is_docker == true)
