---
# tasks file for test-recurse
- name: do combine
  delegate_to: localhost
  command: node . key-combine -d {{ gropius_control_working}}/session
  args:
    chdir: "{{ gropius_root }}"
  register: combine_result
  become: no
  changed_when: false

- name: ensure host spec directory
  delegate_to: localhost
  file:
    path: "{{ gropius_control_working }}/spec"
    state: directory
  become: no

- name: write combine
  delegate_to: localhost
  copy:
    content: "{{ combine_result.stdout }}"
    dest: "{{ gropius_control_working }}/spec/validators.json"
  become: no

- name: do inject
  delegate_to: localhost
  command: node . inject -s {{ gropius_control_working }}/spec/chainSpec.json -v {{ gropius_control_working}}/spec/validators.json
  args:
    chdir: "{{ gropius_root }}"
  register: inject_result
  become: no
  changed_when: false

- name: write combine
  delegate_to: localhost
  copy:
    content: "{{ inject_result.stdout }}"
    dest: "{{ gropius_control_working }}/session/combo.json"
  become: no
