---
dependency:
  name: galaxy
  options:
    role-file: ../../requirements/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: validator0
    image: jrei/systemd-ubuntu:18.04
    groups:
      - builder_bin
      - validator
    privileged: true
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/sbin/init'
    network_mode: host
    environment:
      container: docker
  - name: validator1
    image: jrei/systemd-ubuntu:18.04
    groups:
      - validator
    privileged: true
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/sbin/init'
    network_mode: host
    environment:
      container: docker
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        substrate_repository: 'https://github.com/substrate-developer-hub/substrate-node-template'
        substrate_repository_version: '8b6fe66'
        substrate_network_id: local_testnet
        substrate_chain: /home/subuser/tmp/gropius-validator/spec/chainSpecRaw.raw
        substrate_bin_name: node-template
        gropius_control_working: /home/subuser/tmp/gropius-control
        gropius_root: ../../../../../
      builder_bin:
        gropius_working: /home/subuser/tmp/gropius-build-bin
      builder_spec:
        gropius_working: /home/subuser/tmp/gropius-build-spec
      validator:
        gropius_working: /home/subuser/tmp/gropius-validator
        substrate_user: subuser
        substrate_group: subgroup
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
