---
- hosts: all
  gather_facts: false
  strategy: free
  tasks:
  - name: wait for machine and ssh
    wait_for_connection:
      timeout: 900
      sleep: 10
    retries: 20

- hosts: validator
  roles:
  - gropius-env
  become: yes

- hosts: master-validator
  roles:
  - substrate-build-node
  become: yes

- hosts: validator
  strategy: free
  roles:
  - validator-push-bin
  become: yes

- hosts: validator
  roles:
  - validator-service
  - substrate-keygen
