---
- hosts: all
  gather_facts: false
  strategy: free
  tasks:
  - name: wait for machine and ssh
    wait_for_connection:
      timeout: 5
      sleep: 2
    retries: 3

- hosts: validator
  roles:
  - gropius-env
  become: yes

- hosts: builder_bin
  roles:
  - substrate-build-node
  become: yes

- hosts: validator
  strategy: free
  roles:
  - validator-push-bin
  become: yes

- hosts: validator
  roles:
  - validator-service
  - substrate-keygen
