- hosts: all
  gather_facts: false
  strategy: free
  tasks:
  - name: wait for machine and ssh
    wait_for_connection:
      timeout: 900
      sleep: 10
    retries: 20

- hosts: all
  become: yes
  strategy: free
  roles:
  - substrate-builder
  - { role: node-exporter, when: "node_exporter_enabled|default(false)|bool == true" }
  - substrate-common

- hosts: all
  become: yes
  roles:
  - common

- hosts: validator
  become: yes
  roles:
  - substrate-validator
  - substrate-validator-session-info
