- hosts: all
  gather_facts: false
  strategy: free
  tasks:
  - name: wait for machine and ssh
    wait_for_connection:
      timeout: 900
      sleep: 10
    retries: 20
    

- hosts: all
  become: yes
  strategy: free
  roles:
  - { role: node-exporter, when: "node_exporter_enabled|default(false)|bool == true" }
  - vpnpeer-setup
  - polkadot-common

- hosts: all
  become: yes
  roles:
  - vpnpeer
  - common

- hosts: public
  become: yes
  roles:
  - polkadot-public

- hosts: validator
  become: yes
  roles:
  - polkadot-validator
  - polkadot-validator-session-info
