---
- hosts: non-local
  gather_facts: false
  strategy: free
  tasks:
    - name: wait for machine and ssh
      wait_for_connection:
        timeout: 120
        sleep: 2
      retries: 3

- hosts: localhost
  tasks:
    - debug:
        msg: yeet
  become: no

- hosts: localhost
  roles:
    - infra-build-multi
  vars:
    ansible_groups:
    - temp_builder
    - provider_gcp
    - builder_bin
  become: no

- hosts: all
  roles:
    - role: validator-env-gantree
  become: yes

- hosts: builder_bin
  roles:
    - mock-build-bin
  become: yes

- hosts: localhost
  roles:
    - infra-gcp-node
  vars:
    #ansible_user: root
    state: absent
    ansible_groups:
    - temp_builder
    - provider_do
    - builder_bin
  #become: nos

- hosts: validator:builder_spec
  strategy: free
  roles:
    - validator-push-bin
  become: yes

- hosts: localhost
  roles:
    - control-prepare

- hosts: validator
  serial: 1 # NOTE(ryan): to avoid weird collision on pulling the keys to host
  roles:
    - validator-gen-keys

- hosts: builder_spec
  roles:
    - role: builder-build-spec
      when: 'substrate_use_default_spec|default(false)|bool == false and substrate_chain_argument|default(false)|bool == false'

- hosts: bootnode # NOTE(ryan): currently only supports 1
  roles:
    - role: bootnode-collect-ip
      when: 'substrate_use_default_spec|default(false)|bool == false and substrate_chain_argument|default(false)|bool == false'

- hosts: validator
  roles:
    - role: validator-push-spec
      when: 'substrate_use_default_spec|default(false)|bool == false and substrate_chain_argument|default(false)|bool == false'

- hosts: validator
  roles:
    - validator-service

- hosts: validator
  roles:
    - validator-key-insert

- hosts: validator
  roles:
    - validator-service-restart
