---
- name: download node source
  git:
    repo: https://github.com/substrate-developer-hub/substrate-node-template
    version: '8b6fe66'
    dest: "{{ gropius_path }}/node-src"

- name: compile-node
  shell: |
    cargo build --release
  args:
    chdir: "{{ gropius_path }}/node-src/"
  changed_when: false

- name: create host bin directory
  local_action:
    module: file
    path: "{{ gropius_control_path }}/bin"
    state: directory
  become: no

- name: download node bin to host
  fetch:
    src: "{{ gropius_path }}/node-src/target/release/node-template"
    dest: "{{ gropius_control_path }}/bin/node-template"
    flat: true
