---
- name: download node source
  git:
    repo: https://github.com/substrate-developer-hub/substrate-node-template
    version: '8b6fe66'
    dest: /tmp/gropius/node-src

- name: compile-node
  shell: |
    cargo build --release
  args:
    chdir: /tmp/gropius/node-src/
  changed_when: false

- name: create host bin directory
  local_action:
    module: file
    path: /tmp/gropius_host/bin
    state: directory
  become: no

- name: download node bin to host
  fetch:
    src: /tmp/gropius/node-src/target/release/node-template
    dest: /tmp/gropius_host/bin/node-template
    flat: true
