---

- name: install pollock dependencies
  apt:
    update_cache: yes
    name:
      - curl
      - python-setuptools
      - python3
      - python3-pip
      - python3-setuptools

- name: install pollock
  pip:
    executable: pip3
    name: pollock
    version: '0.1.1'
    extra_args: -i https://test.pypi.org/simple/

# taken from https://getsubstrate.io
- name: install substrate build requirements for ubuntu
  apt:
    pkg:
    - cmake
    - pkg-config
    - libssl-dev
    - git
    - gcc
    - build-essential
    - clang
    - libclang-dev

- name: setup cargo and rustup
  include_role:
    name: ansible-role-cargo

- name: configure rustup
  shell: |
    rustup default stable
    rustup update nightly
    rustup target add wasm32-unknown-unknown --toolchain nightly
  changed_when: false
