---
- name: download node source
  git:
    repo: https://github.com/substrate-developer-hub/substrate-node-template
    version: '8b6fe66'
    dest: /tmp/gropius/node-src

- name: compile-node
  shell: |
    cargo build --release
  args:
    chdir: /tmp/gropius/node-src/
  changed_when: false

- name: install node binary
  shell: |
    cp /tmp/gropius/node-src/target/release/node-template /usr/local/bin/node-template
  changed_when: false

- name: create chainspec directory
  file:
    path: /tmp/gropius/spec
    state: directory

- name: get chain spec
  shell: |
    node-template build-spec > ./customSpec.json
  args:
    chdir: /tmp/gropius/spec/
  changed_when: false

- name: get chain spec
  shell: |
    node-template build-spec --chain ./customSpec.json --raw > ./customSpecRaw.raw
  args:
    chdir: /tmp/gropius/spec/
  changed_when: false