---
- name: selector
  import_role:
    name: infra-gcp-node
  vars:
    instance_name: "{{ item.instance_name }}"
    zone: "{{ item.zone }}"
    region: "{{ item.region }}"
    machine_type: "{{ item.machine_type }}"
    gcp_project: "{{ item.gcp_project }}"
    ssh_user: "{{ item.ssh_user }}"
    ssh_key: "{{ item.ssh_key }}"
    ansible_user: "{{ item.ssh_key }}"
    state: "{{ item.state }}"
  async: 600
  retries: 3
  register: infra_promises
