---
# tasks file for substrate
- name: create substrate group
  group:
    name: substrate
    state: present

- name: add gropius_user user
  user:
    name: gropius_user
    group: substrate
    append: true

# - name: save networkState
#   uri:
#     url: http://localhost:9933
#     method: "POST"
#     body_format: json
#     body: |
#       { "jsonrpc":"2.0", "method":"system_networkState", "params":[], "id":1 }
#   register: network_state
#   until: network_state.status == 200
#   retries: 5
#   delay: 5

# - name: set peer id as fact
#   set_fact:
#     p2p_peer_id: "{{ network_state.json.result.peerId }}"
