---
# tasks file for substrate
- name: create substrate group
  group:
    name: substrate
    state: present

- name: add gropius_user user
  user:
    name: gropius_user
    group: substrate
    append: yes
