---
# added become: yes

- name: ensure home dir
  file:
    path: '/home/{{ substrate_user }}'
    state: directory

- name: check for mnemonic
  stat:
    path: /home/{{ substrate_user }}/mnemonic
  register: mnemonic_check

# note: I deleted xargs from a couple of these commands because the AWS machine was upset
- name: generate mnemonic
  shell: |
    set -o pipefail

    inspect_result=$(/usr/local/bin/subkey --ed25519 generate)

    mnemonic=$(echo -n "${inspect_result}" | grep "Secret phrase" | cut -d'`' -f2)

    echo ${mnemonic}
  args:
    executable: /bin/bash
  register: mnemonic
  when: mnemonic_check.stat.exists == False

- name: write mnemonic to disk on remote host
  copy:
    content: '{{ mnemonic.stdout }}'
    dest: /home/{{ substrate_user }}/mnemonic
  become: yes
  when: mnemonic_check.stat.exists == False

- name: save session info
  shell: |
    set -o pipefail
    crypto="{{ item }}"

    inspect_result=$(cat /home/{{ substrate_user }}/mnemonic | xargs --null /usr/local/bin/subkey --${crypto} inspect)

    public_key=$(echo -n "${inspect_result}" | grep "Public key" | cut -d':' -f2 | tr -d '[:space:]')
    address=$(echo -n "${inspect_result}" | grep "Address" | cut -d':' -f2 | tr -d '[:space:]')

    printf '%b\n' "{{ item }}:\n  address: '${address}'\n  public_key: '${public_key}'"
  args:
    executable: /bin/bash
  register: session
  loop:
    - ed25519
    - sr25519
  changed_when: False

- name: get node key
  shell: |
    {{ substrate_bin_name }} --node-key-file /home/{{ substrate_user }}/.local/share/{{ substrate_bin_name }}/chains/{{ substrate_network_id }}/network/secret_ed25519 > nodeoutput 2>&1 &

    sleep 3

    pkill {{ substrate_bin_name }}

    node_id=$(grep "Local node identity is:" < nodeoutput | sed 's/.*://' | tr -d " ")

    echo ${node_id}
  register: node_key

- name: get bootnode public ip
  ipify_facts:
  register: bootnode_ip
  when: (not is_docker is defined) or (not is_docker == true)

- name: write session info to disk on remote host
  become: yes
  template:
    src: session.yaml.j2
    dest: /home/{{ substrate_user }}/session.{{ substrate_network_id }}.yaml
    mode: 0666

- name: ensure host session directory
  delegate_to: localhost
  file:
    path: '{{ gantree_control_working }}/session'
    state: directory
  become: no

- name: retrieve session info
  fetch:
    src: '/home/{{ substrate_user }}/session.{{ substrate_network_id }}.yaml'
    dest: '{{ gantree_control_working }}/session/{{ inventory_hostname }}.{{ substrate_network_id }}.yaml'
    flat: yes
  retries: 2

- name: change owner of substrate user keystore
  become: yes
  file:
    path: /home/{{ substrate_user }}/.local/share/{{ substrate_bin_name }}/chains/{{ substrate_network_id }}
    owner: '{{ substrate_user }}'
    group: '{{ substrate_group }}'
    recurse: yes
    mode: 0755
