---
- name: associate elastic ip
  ec2_eip:
    device_id: "{{ item.instance_id }}"
    region: "{{ region }}"
    state: "{{ state }}"
    release_on_disassociation: yes
  with_items: "{{ ec2.instances }}"
  register: elastic_ip
