---
- import_tasks: 2_instance_info.yml
  when: state != 'absent'

- name: associate elastic ip
  delegate_to: localhost
  ec2_eip:
    device_id: "{{ ec2inst_res.instance_id }}"
    region: "{{ region }}"
    state: "{{ state }}"
    release_on_disassociation: yes
  register: elastic_ip
  when: state != 'absent'
