---
# NOTE(ryan) 2_instance_info and 2_instance both register 'ec2'
- name: ec2 instance info
  ec2_instance:
    region: "{{ region }}"
    filters:  # NOTE(ryan): default filter borks with character limit exceeded
      "tag:Name": "inst-{{ instance_name }}"
      "tag:not_terminated": "true"
  register: ec2inst_res_all
  no_log: yes

- name: set ec2inst_res fact
  set_fact:
    ec2inst_res: "{{ ec2inst_res_all.instances[0] }}"
