---
# TODO(ryan) is this comment still applicable?
# Terminate every running instance in a region. Use with EXTREME caution.
- name: refresh vpc net info
  ec2_vpc_net_info:
    region: "{{ region }}"
    filters:
      "tag:Name": "vpc-{{ instance_name }}"
  register: vpc_result

- name: refresh vpc subnet info
  ec2_vpc_subnet_info:
    region: "{{ region }}"
    filters:
      "tag:Name": "vpcsn-{{ instance_name }}"
  register: subnet_result

- name: refresh internet gateway info
  ec2_vpc_igw_info:
    region: "{{ region }}"
    filters:
      "tag:Name": "igw-{{ instance_name }}"
  register: igw_result

- name: refresh route table info
  ec2_vpc_route_table_info:
    region: "{{ region }}"
    filters:
      "tag:Name": "vpcrt-{{ instance_name }}"
  register: routetable_result
